services:
  frontend:
    image: ghcr.io/alberta2514640/clutter-frontend:latest
    container_name: clutter ##name of the container
    ports:
      - "8080:3000"

    restart: unless-stopped

    healthcheck:
      test: curl --fail http://localhost:3000/ping || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s